export const refs = {
  body: document.querySelector('body'),
  listCategories: document.getElementById('jsListCategories'),
  listSuportUkraine: document.getElementById('jsListSuportUkraine'),
  inputSwitch: document.getElementById('switchMode'),
  mainPage: document.getElementById('mainPage'),
  scrDownBtn: document.getElementById('go-down'),
  popup: document.querySelector('.popup'),
  openModalBtn: document.querySelector('[data-modal]'),
  closeModalBtn: document.querySelector('[data-modal-close]'),
  modal: document.querySelector('.renderModal'),
  allCategories: document.querySelector('.allCategories'),
  singUpButton: document.querySelector('.userButton'),
  modalAuth: document.querySelector('#modalAuth'),
  closeBtn: document.querySelector('#closeBtn'),
  formModalAuth: document.getElementById('formAuth'),
};
